### ISSUE TITLE
Star count?

### ISSUE THREAD

**Issue by eliocamp** [ChadGoymer/githapi#217]
I was using this package to automatically populate some information on my repos, including start counts using `githapi::gh_repository(repo)$stargazers_count`. At some point, there was a change in function names and now the relevant function seems to be `githapi::view_repository(repo)`, but it doesn't return `stargazers_count`. 

Is this still possible? Which function should I use?

**Comment by ChadGoymer** [comment]
Hi @eliocamp, apologies I was not aware anyone was using the package yet. I have been rebuilding it and hoping to release it to CRAN soon. You are correct, `view_repository()` is intended to replace `gh_repository()`. I will add the `stargazers_count` back in for you.
