### ISSUE TITLE
Code example in docs for view_branches contains example from view_label

### ISSUE THREAD

**Issue by iceiony** [ChadGoymer/githapi#227]
## Description

The code examples in `view_branches`  contains an example for `view_label` rather than `view_branch`:
```R
  # View all branches in a repository
  view_branches("ChadGoymer/githapi")

  # View a single branch
  view_label("new-branch", "ChadGoymer/githapi")
```

## Proposed Solution

Replace the example code with the appropriate one.

**Comment by ChadGoymer** [comment]
Thanks. this has been fixed in pull request #229
